version: "3"

services:
    sns_sample:
        build:
            context: .
            dockerfile: DockerFile
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: sns_web
        ports:
            - 5000:5000
        #tty: true
        environment:
            - VIRTUAL_HOST=sns.sample
        networks:
            - sns-sample-network
    
    
networks:
    sns-sample-network:
        name: sns_sample_network